# Generated by Django 3.2.7 on 2021-10-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extended_orders',
            new_name='Extended_order',
        ),
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
