# Generated by Django 3.2.7 on 2021-10-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20211004_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
