# Generated by Django 3.2 on 2021-10-10 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extended_order',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='order',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 23, 56, 32, 743763)),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 23, 56, 32, 743763)),
        ),
    ]
