# Generated by Django 3.2 on 2021-10-11 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_auto_20211011_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ext_num',
            field=models.IntegerField(default=0, help_text='This field changes automatically, just skip this field.'),
        ),
        migrations.AlterField(
            model_name='extended_order',
            name='new_from_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 19, 52, 38, 106254)),
        ),
        migrations.AlterField(
            model_name='extended_order',
            name='new_to_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 19, 52, 38, 106254)),
        ),
        migrations.AlterField(
            model_name='order',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 19, 52, 38, 106255)),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 19, 52, 38, 106255)),
        ),
    ]
